# Site settings
title: Solace Samples SEMP
baseurl: "/solace-samples-semp" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-semp

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
docs-semp-home: http://docs.solace.com/SEMP/SEMP-Home.htm
docs-concepts: http://docs.solace.com/SEMP/SEMP-Concepts.htm
docs-architecture: http://docs.solace.com/SEMP/SEMP-API-Archit.htm
docs-http-responses: http://docs.solace.com/SEMP/SEMP-API-Protocol.htm#HTTP-content
docs-concepts-paging: http://docs.solace.com/SEMP/SEMP-API-Archit.htm#Paginati
docs-concepts-uri: http://docs.solace.com/SEMP/SEMP-API-Protocol.htm#URI
docs-api: http://docs.solace.com/swagger-ui/index.html
docs-schema: http://docs.solace.com/SEMP/SEMP-API-Archit.htm#SEMP
docs-semp-legacy: http://docs.solace.com/SEMP/Legacy-SEMP.htm
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm

#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
